<?php
// Permissões disponíveis no sistema
return [
    'admin' => [
        'view_dashboard' => true,
        'view_all_products' => true,
        'edit_all_products' => true,
        'view_all_clients' => true,
        'edit_all_clients' => true,
        'view_all_sales' => true,
        'edit_all_sales' => true,
        'view_all_stock' => true,
        'edit_all_stock' => true,
        'view_all_production' => true,
        'edit_all_production' => true,
        'view_all_pdv' => true,
        'edit_all_pdv' => true,
        'view_reports' => true,
        'manage_users' => true,
        'manage_permissions' => true,
        'view_settings' => true,
        'view_profile' => true,
    ],
    'employee' => [
        'view_dashboard' => true,
        'view_own_products' => true,
        'edit_own_products' => true,
        'view_own_clients' => true,
        'edit_own_clients' => true,
        'view_own_sales' => true,
        'edit_own_sales' => true,
        'view_own_stock' => true,
        'edit_own_stock' => true,
        'view_own_production' => true,
        'edit_own_production' => true,
        'view_own_pdv' => true,
        'edit_own_pdv' => true,
        'view_reports' => false,
        'manage_users' => false,
        'manage_permissions' => false,
        'view_settings' => true,
        'view_profile' => true,
    ],
    'client' => [
        'view_dashboard' => true,
        'view_own_data' => true,
        'edit_own_data' => false,
        'view_own_products' => false,
        'view_own_clients' => false,
        'view_own_sales' => false,
        'view_own_stock' => false,
        'view_own_production' => false,
        'view_own_pdv' => false,
        'view_reports' => false,
        'manage_users' => false,
        'manage_permissions' => false,
        'view_settings' => true,
        'view_profile' => true,
    ],
    'user' => [
        'view_dashboard' => true,
        'view_own_products' => true,
        'edit_own_products' => true,
        'view_own_clients' => true,
        'edit_own_clients' => true,
        'view_own_sales' => true,
        'edit_own_sales' => true,
        'view_own_stock' => true,
        'edit_own_stock' => true,
        'view_own_production' => true,
        'edit_own_production' => true,
        'view_own_pdv' => true,
        'edit_own_pdv' => true,
        'view_reports' => false,
        'manage_users' => false,
        'manage_permissions' => false,
        'view_settings' => true,
        'view_profile' => true,
    ]
];
